FROM node:8.12 as node812


COPY ui-dev.entrypoint.sh /opt/
RUN chmod u+x /opt/ui-dev.entrypoint.sh



#COPY ./scripts/buildll  .
#RUN  chmod +x buildll

# RUN npm install --registry=https://registry.npm.taobao.org

WORKDIR /opt/scripts

ENTRYPOINT /opt/ui-dev.entrypoint.sh







