version: '3'

services:

  ui:
    build:
      context: ./
      dockerfile: ./uranus-stage-ui/Dockerfile.nginx-ui-dist
      args:
        BUILD_DIST: ${BUILD_DIST}
        HOST_IP: ${HOST_IP}
        JAVASRV_IP: ${JAVASRV_IP}
        IMGSRV_PORT: 3300
    image: "xiliangma/uranus-ui-container:v1"
    ports:
        - "80:80"
        - "443:443"
        - "4000:4000"
    depends_on:
      - proxy
    links:
      - proxy:rancher-proxy
    volumes:
      - ./build_dir:/build_dir/
      - /opt/uranus/log/nginx:/var/logs
    restart: unless-stopped

  proxy:
    build:
      context: ./
      dockerfile: ./proxy_dev_server/Dockerfile.proxy-rancher
    image: "xiliangma/uranus-rancher-proxy-container:v1"
    ports:
        - "8088:8088"
    restart: unless-stopped

  imgsrv:
    build:
      context: uranus-image-server
      dockerfile: ./Dockerfile.image-server
      args:
        TARGET_IP: 15.164.158.198
        AUTH: token-nkv6b:hmxlmp6c98hklcp5qmmx9js8f6d48kcjptl4k4gc2wwrnddmsjtfwc
    image: "xiliangma/uranus-img-server-container:v1"
    ports:
        - "3300:3300"
    restart: unless-stopped

  ftpsrv:
    build:
      context: uranus-ftp-server
      dockerfile: ./Dockerfile.vsftpd
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    image: "xiliangma/uranus-ftp-server:v1"
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:8000:21
      - 21100-21110:21100-21110
    volumes:
      - /opt/uranus/ftphome:/home/vsftpd
      - /opt/uranus/ftplogs:/var/log/
    restart: unless-stopped




