version: '3'
services:
  ui:
    build:
      context: ./
      dockerfile: ./uranus-stage-ui/Dockerfile.nginx-ui-dist
      args:
        BUILD_DIST: ${BUILD_DIST}
        HOST_IP: ${HOST_IP}
        JAVASRV_IP: ${JAVASRV_IP}
        IMGSRV_PORT: 3330
    image: "xiliangma/uranus-ui-container:v1"
    ports:
        - "80:80"
        - "443:443"
        - "4000:4000"
    depends_on:
      - proxy
    links:
      - proxy:rancher-proxy
    volumes:
      - ./build_dir:/build_dir/
      - /opt/uranus/log/nginx:/var/logs

  proxy:
    build:
      context: ./
      dockerfile: ./proxy_dev_server/Dockerfile.proxy-rancher
    image: "xiliangma/urnaus-rancher-proxy-container:v1"
    ports:
        - "8088:8088"

  img:
    build:
      context: ./image-container
      dockerfile: ./Dockerfile.image-server
      args:
        TARGET_IP: 15.164.158.198
        AUTH: token-nkv6b:hmxlmp6c98hklcp5qmmx9js8f6d48kcjptl4k4gc2wwrnddmsjtfwc
    image: "xiliangma/urnaus-img-server-container:v1"   
    ports:
        - "3300:3300"

