version: '3'
services:
  ui:
    build:
      context: ./
      dockerfile: ./uranus-stage-ui/Dockerfile.nginx-ui-dist
    ports:
        - "80:80"
        - "443:443"
        - "4000:4000"
    environment:
        HOST_IP: "192.168.0.130"
    depends_on:
      - proxy
    links:
      - proxy:rancher-proxy

  proxy:
    build:
      context: ./
      dockerfile: ./proxy_dev_server/Dockerfile.proxy-rancher
    ports:
        - "8088:8088"
