apiVersion: apps/v1
kind: Deployment
metadata:
  name: uranus-stage-rancher-proxy
  labels:
    app: uranus-stage-rancher-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uranus-stage-rancher-proxy
  template:
    metadata:
      labels:
        app: uranus-stage-rancher-proxy
    spec:
      containers:
      - name: uranus-stage-rancher-proxy-container
        image: xiliangma/urnaus-rancher-proxy-container:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: rancher_proxy_port
          containerPort: 8088
          #hostPort: 8088